########################
# RUN CONFIGURATION #
########################

run_name: MLL1_IDR3_XPO1_NPM1cCTREM_NUP214Cterm




target:
  whole_proteins:
    - name: XPO1


  fasta:
    - name: NPM1c_CTERM
      sequence: KKSIRDTPAKNAQKSNQNGKDSKPSSTPRSKGQESFKKQEKTPKTPKGPSSVEDIKAKMQASIEKGGSLPKVEAKFINYVKNCFRMTDQEAIQDLCLAVEEVSLRK
  
  segments:
    - protein: NUP214
      name: NUP214_CTERM
      start: 1839
      end: end

    - protein: KMT2A
      name: MLL1_IDR3
      start: 610
      end: 810



########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta