########################
# RUN CONFIGURATION #
########################

run_name: ENL_KAT7

bait:
  whole_proteins:
    - name: MLLT1


target:
  txt_file: KAT7_targets.txt  



########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta