########################
# RUN CONFIGURATION #
########################

run_name: ENL_DOT1L
bait:
  whole_proteins:
    - name: MLLT1


target:
  whole_proteins:
    #- name: KAT6A
    #- name: BRPF1
    #- name: ING5
    #- name: MEAF6 
    - name: DOT1L
    - name: MLLT6
    - name: MLLT10



########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta