########################
# RUN CONFIGURATION #
########################

run_name: MLL1_IDR3_MEN1_NPM1c_XPO1

bait:
  segments:
    - protein: KMT2A
      name: MDB_IBM_to_IDR3
      start: 600
      end: 810
    

    

  #txt_file: KAT7_targets.txt

target:
  whole_proteins:
    - name: XPO1

  fasta:
    - name: NPM1c
      sequence: MEDSMDMDMSPLRPQNYLFGCELKADKDYHFKVDNDENEHQLSLRTVSLGAGAKDELHIVEAEAMNYEGSPIKVTLATLKMSVQPTVSLGGFEITPPVVLRLKCGSGPVHISGQHLVAVEEDAESEDEEEEDVKLLSISGKRSAPGGGSKVPQKKVKLAADEDDDDDDEEDDDEDDDDDDFDDEEAEEKAPVKKSIRDTPAKNAQKSNQNGKDSKPSSTPRSKGQESFKKQEKTPKTPKGPSSVEDIKAKMQASIEKGGSLPKVEAKFINYVKNCFRMTDQEAIQDLCLAVEEVSLRK
  
  #segments:
  #  - protein: NUP98
  #    name: NUP98_FG
  #    start: 1
  #    end: 500



########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta