########################
# RUN CONFIGURATION #
########################

run_name: ESR1_vs_MED1

bait:
  whole_proteins:
      - name: ESR1



target:
  whole_proteins:
      - name: MLL1_IDR3_XPO1_NPM1cCTREM_NUP214Cterm



########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta