########################
# RUN CONFIGURATION #
########################

run_name: MLL1_TAD_seg_EP300

bait:
  segments:
    - protein: KMT2A
      name: IDR11_9aaTAD
      start: 2675
      end: 2875
    
    
    

  #txt_file: KAT7_targets.txt

target:
  whole_proteins:
    - name: EP300
  
  #segments:
  #  - protein: NUP98
  #    name: NUP98_FG
  #    start: 1
  #    end: 500



########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta