########################
# RUN CONFIGURATION #
########################

run_name: MLL1_IDR3_NPM1c_XPO1_NUP214

bait:
  segments:
    - protein: KMT2A
      name: IDR3
      start: 600
      end: 810
    


target:
  whole_proteins:
    - name: XPO1
    - name: NUP214

  fasta:
    - name: NPM1c
      sequence: MEDSMDMDMSPLRPQNYLFGCELKADKDYHFKVDNDENEHQLSLRTVSLGAGAKDELHIVEAEAMNYEGSPIKVTLATLKMSVQPTVSLGGFEITPPVVLRLKCGSGPVHISGQHLVAVEEDAESEDEEEEDVKLLSISGKRSAPGGGSKVPQKKVKLAADEDDDDDDEEDDDEDDDDDDFDDEEAEEKAPVKKSIRDTPAKNAQKSNQNGKDSKPSSTPRSKGQESFKKQEKTPKTPKGPSSVEDIKAKMQASIEKGGSLPKVEAKFINYVKNCFRMTDQEAIQDLCLAVEEVSLRK
  
  txt_file: KAT7_targets.txt


########################
# GLOBAL CONFIGURATION #
########################

fasta_database_file : UP000005640_9606.fasta